import { z } from 'zod';

export const shortQuoteSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        price: z.coerce.number(),
        change: z.coerce.number(),
        volume: z.coerce.number(),
    }),
);

export const quoteSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        name: z.coerce.string(),
        exchange: z.coerce.string(),
        price: z.coerce.number(),
        changePercentage: z.coerce.number(),
        change: z.coerce.number(),
        volume: z.coerce.number(),
        dayLow: z.coerce.number(),
        dayHigh: z.coerce.number(),
        yearHigh: z.coerce.number(),
        yearLow: z.coerce.number(),
        marketCap: z.nullable(z.coerce.number()),
        priceAvg50: z.coerce.number(),
        priceAvg200: z.coerce.number(),
        open: z.coerce.number(),
        previousClose: z.coerce.number(),
        timestamp: z.coerce.number(),
    }),
);

export const lightChartSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        date: z.coerce.date(),
        price: z.coerce.number(),
        volume: z.coerce.number(),
    }),
);

export const unadjustedSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        date: z.coerce.date(),
        adjOpen: z.coerce.number(),
        adjHigh: z.coerce.number(),
        adjLow: z.coerce.number(),
        adjClose: z.coerce.number(),
        volume: z.coerce.number(),
    }),
);

export const fullChartSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        date: z.coerce.date(),
        open: z.coerce.number(),
        high: z.coerce.number(),
        low: z.coerce.number(),
        close: z.coerce.number(),
        volume: z.coerce.number(),
        change: z.coerce.number(),
        changePercent: z.coerce.number(),
        vwap: z.coerce.number(),
    }),
);

export const intradayChartSchema = z.array(
    z.object({
        date: z.coerce.date(),
        open: z.coerce.number(),
        low: z.coerce.number(),
        high: z.coerce.number(),
        close: z.coerce.number(),
        volume: z.coerce.number(),
    }),
);

export const searchSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        name: z.coerce.string(),
        currency: z.coerce.string(),
        exchangeFullName: z.nullable(z.coerce.string()),
        exchange: z.coerce.string(),
    }),
);

export const companyProfileSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        price: z.coerce.number(),
        marketCap: z.nullable(z.coerce.number()),
        beta: z.coerce.number(),
        lastDividend: z.coerce.number(),
        range: z.coerce.string(),
        change: z.coerce.number(),
        changePercentage: z.coerce.number(),
        volume: z.coerce.number(),
        averageVolume: z.coerce.number(),
        companyName: z.coerce.string(),
        currency: z.coerce.string(),
        cik: z.nullable(z.coerce.string()),
        isin: z.nullable(z.coerce.string()),
        cusip: z.nullable(z.coerce.string()),
        exchangeFullName: z.nullable(z.coerce.string()),
        exchange: z.coerce.string(),
        industry: z.coerce.string(),
        website: z.nullable(z.url()),
        description: z.coerce.string(),
        ceo: z.nullable(z.coerce.string()),
        sector: z.coerce.string(),
        country: z.nullable(z.coerce.string()),
        fullTimeEmployees: z.nullable(z.coerce.string()),
        phone: z.nullable(z.coerce.string()),
        address: z.nullable(z.coerce.string()),
        city: z.nullable(z.coerce.string()),
        state: z.nullable(z.coerce.string()),
        zip: z.nullable(z.coerce.string()),
        image: z.url(),
        ipoDate: z.coerce.date(),
        defaultImage: z.boolean(),
        isEtf: z.boolean(),
        isActivelyTrading: z.boolean(),
        isAdr: z.boolean(),
        isFund: z.boolean(),
    }),
);

export const employeeCount = z.array(
    z.object({
        symbol: z.coerce.string(),
        cik: z.coerce.string(),
        acceptanceTime: z.coerce.date(),
        periodOfReport: z.coerce.date(),
        companyName: z.coerce.string(),
        formType: z.coerce.string(),
        filingDate: z.coerce.date(),
        employeeCount: z.coerce.number(),
        source: z.url(),
    }),
);

export const marketCap = z.array(
    z.object({
        symbol: z.coerce.string(),
        date: z.coerce.date(),
        marketCap: z.coerce.number(),
    }),
);

export const stockListSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        name: z.coerce.string(),
        exchange: z.coerce.string(),
        currency: z.coerce.string(),
    }),
);

export const cryptoListSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        name: z.coerce.string(),
        exchange: z.coerce.string(),
        icoDate: z.coerce.date(),
        circulatingSupply: z.nullable(z.coerce.number()),
        totalSupply: z.nullable(z.coerce.number()),
    }),
);

export const forexListSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        fromCurrency: z.coerce.string(),
        fromName: z.coerce.string(),
        toCurrency: z.coerce.string(),
        toName: z.coerce.string(),
    }),
);

export const commoditiesListSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        name: z.coerce.string(),
        exchange: z.nullable(z.coerce.string()),
        tradeMonth: z.coerce.string(),
        currency: z.coerce.string(),
    }),
);

export const marketHoursSchema = z.array(
    z.object({
        exchange: z.coerce.string(),
        name: z.coerce.string(),
        openingHour: z.coerce.string(),
        closingHour: z.coerce.string(),
        timezone: z.coerce.string(),
        isMarketOpen: z.boolean(),
    }),
);

export const holidaysSchema = z.array(
    z.object({
        exchange: z.coerce.string(),
        date: z.coerce.date(),
        name: z.coerce.string(),
        isClosed: z.nullable(z.boolean()),
        adjOpenTime: z.nullable(z.coerce.string()),
        adjCloseTime: z.nullable(z.coerce.string()),
    }),
);

export const keyMetricsSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        date: z.coerce.date(),
        fiscalYear: z.coerce.string(),
        period: z.coerce.string(),
        reportedCurrency: z.coerce.string(),
        marketCap: z.coerce.number(),
        enterpriseValue: z.coerce.number(),
        evToSales: z.coerce.number(),
        evToOperatingCashFlow: z.coerce.number(),
        evToFreeCashFlow: z.coerce.number(),
        evToEBITDA: z.coerce.number(),
        netDebtToEBITDA: z.coerce.number(),
        currentRatio: z.coerce.number(),
        incomeQuality: z.coerce.number(),
        grahamNumber: z.coerce.number(),
        grahamNetNet: z.coerce.number(),
        taxBurden: z.coerce.number(),
        interestBurden: z.coerce.number(),
        workingCapital: z.coerce.number(),
        investedCapital: z.coerce.number(),
        returnOnAssets: z.coerce.number(),
        operatingReturnOnAssets: z.coerce.number(),
        returnOnTangibleAssets: z.coerce.number(),
        returnOnEquity: z.coerce.number(),
        returnOnInvestedCapital: z.coerce.number(),
        returnOnCapitalEmployed: z.coerce.number(),
        earningsYield: z.coerce.number(),
        freeCashFlowYield: z.coerce.number(),
        capexToOperatingCashFlow: z.coerce.number(),
        capexToDepreciation: z.coerce.number(),
        capexToRevenue: z.coerce.number(),
        salesGeneralAndAdministrativeToRevenue: z.coerce.number(),
        researchAndDevelopementToRevenue: z.coerce.number(),
        stockBasedCompensationToRevenue: z.coerce.number(),
        intangiblesToTotalAssets: z.coerce.number(),
        averageReceivables: z.coerce.number(),
        averagePayables: z.coerce.number(),
        averageInventory: z.coerce.number(),
        daysOfSalesOutstanding: z.coerce.number(),
        daysOfPayablesOutstanding: z.coerce.number(),
        daysOfInventoryOutstanding: z.coerce.number(),
        operatingCycle: z.coerce.number(),
        cashConversionCycle: z.coerce.number(),
        freeCashFlowToEquity: z.coerce.number(),
        freeCashFlowToFirm: z.coerce.number(),
        tangibleAssetValue: z.coerce.number(),
        netCurrentAssetValue: z.coerce.number(),
    }),
);

export const ratiosSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        date: z.coerce.date(),
        fiscalYear: z.coerce.string(),
        period: z.coerce.string(),
        reportedCurrency: z.coerce.string(),
        grossProfitMargin: z.coerce.number(),
        ebitMargin: z.coerce.number(),
        ebitdaMargin: z.coerce.number(),
        operatingProfitMargin: z.coerce.number(),
        pretaxProfitMargin: z.coerce.number(),
        continuousOperationsProfitMargin: z.coerce.number(),
        netProfitMargin: z.coerce.number(),
        bottomLineProfitMargin: z.coerce.number(),
        receivablesTurnover: z.coerce.number(),
        payablesTurnover: z.coerce.number(),
        inventoryTurnover: z.coerce.number(),
        fixedAssetTurnover: z.coerce.number(),
        assetTurnover: z.coerce.number(),
        currentRatio: z.coerce.number(),
        quickRatio: z.coerce.number(),
        solvencyRatio: z.coerce.number(),
        cashRatio: z.coerce.number(),
        priceToEarningsRatio: z.coerce.number(),
        priceToEarningsGrowthRatio: z.coerce.number(),
        forwardPriceToEarningsGrowthRatio: z.coerce.number(),
        priceToBookRatio: z.coerce.number(),
        priceToSalesRatio: z.coerce.number(),
        priceToFreeCashFlowRatio: z.coerce.number(),
        priceToOperatingCashFlowRatio: z.coerce.number(),
        debtToAssetsRatio: z.coerce.number(),
        debtToEquityRatio: z.coerce.number(),
        debtToCapitalRatio: z.coerce.number(),
        longTermDebtToCapitalRatio: z.coerce.number(),
        financialLeverageRatio: z.coerce.number(),
        workingCapitalTurnoverRatio: z.coerce.number(),
        operatingCashFlowRatio: z.coerce.number(),
        operatingCashFlowSalesRatio: z.coerce.number(),
        freeCashFlowOperatingCashFlowRatio: z.coerce.number(),
        debtServiceCoverageRatio: z.coerce.number(),
        interestCoverageRatio: z.coerce.number(),
        shortTermOperatingCashFlowCoverageRatio: z.coerce.number(),
        operatingCashFlowCoverageRatio: z.coerce.number(),
        capitalExpenditureCoverageRatio: z.coerce.number(),
        dividendPaidAndCapexCoverageRatio: z.coerce.number(),
        dividendPayoutRatio: z.coerce.number(),
        dividendYield: z.coerce.number(),
        dividendYieldPercentage: z.coerce.number(),
        revenuePerShare: z.coerce.number(),
        netIncomePerShare: z.coerce.number(),
        interestDebtPerShare: z.coerce.number(),
        cashPerShare: z.coerce.number(),
        bookValuePerShare: z.coerce.number(),
        tangibleBookValuePerShare: z.coerce.number(),
        shareholdersEquityPerShare: z.coerce.number(),
        operatingCashFlowPerShare: z.coerce.number(),
        capexPerShare: z.coerce.number(),
        freeCashFlowPerShare: z.coerce.number(),
        netIncomePerEBT: z.coerce.number(),
        ebtPerEbit: z.coerce.number(),
        priceToFairValue: z.coerce.number(),
        debtToMarketCap: z.coerce.number(),
        effectiveTaxRate: z.coerce.number(),
        enterpriseValueMultiple: z.coerce.number(),
    }),
);

export const indicatorSchema = z.object({
    date: z.coerce.date(),
    open: z.coerce.number(),
    high: z.coerce.number(),
    low: z.coerce.number(),
    close: z.coerce.number(),
    volume: z.coerce.number(),
});

export const latestSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        calendarYear: z.coerce.number(),
        period: z.coerce.string(),
        date: z.coerce.date(),
        dateAdded: z.coerce.date(),
    }),
);

export const cashFlowSchema = z.array(
    z.object({
        date: z.coerce.date(),
        filingDate: z.coerce.date(),
        acceptedDate: z.coerce.date(),
        symbol: z.coerce.string(),
        reportedCurrency: z.coerce.string(),
        cik: z.coerce.string(),
        fiscalYear: z.coerce.string(),
        period: z.coerce.string(),
        netIncome: z.coerce.number(),
        depreciationAndAmortization: z.coerce.number(),
        deferredIncomeTax: z.coerce.number(),
        stockBasedCompensation: z.coerce.number(),
        changeInWorkingCapital: z.coerce.number(),
        accountsReceivables: z.coerce.number(),
        inventory: z.coerce.number(),
        accountsPayables: z.coerce.number(),
        otherWorkingCapital: z.coerce.number(),
        otherNonCashItems: z.coerce.number(),
        netCashProvidedByOperatingActivities: z.coerce.number(),
        investmentsInPropertyPlantAndEquipment: z.coerce.number(),
        acquisitionsNet: z.coerce.number(),
        purchasesOfInvestments: z.coerce.number(),
        salesMaturitiesOfInvestments: z.coerce.number(),
        otherInvestingActivities: z.coerce.number(),
        netCashProvidedByInvestingActivities: z.coerce.number(),
        netDebtIssuance: z.coerce.number(),
        longTermNetDebtIssuance: z.coerce.number(),
        shortTermNetDebtIssuance: z.coerce.number(),
        netStockIssuance: z.coerce.number(),
        netCommonStockIssuance: z.coerce.number(),
        commonStockIssuance: z.coerce.number(),
        commonStockRepurchased: z.coerce.number(),
        netPreferredStockIssuance: z.coerce.number(),
        netDividendsPaid: z.coerce.number(),
        commonDividendsPaid: z.coerce.number(),
        preferredDividendsPaid: z.coerce.number(),
        otherFinancingActivities: z.coerce.number(),
        netCashProvidedByFinancingActivities: z.coerce.number(),
        effectOfForexChangesOnCash: z.coerce.number(),
        netChangeInCash: z.coerce.number(),
        cashAtEndOfPeriod: z.coerce.number(),
        cashAtBeginningOfPeriod: z.coerce.number(),
        operatingCashFlow: z.coerce.number(),
        capitalExpenditure: z.coerce.number(),
        freeCashFlow: z.coerce.number(),
        incomeTaxesPaid: z.coerce.number(),
        interestPaid: z.coerce.number(),
    }),
);

export const balanceSheetSchema = z.array(
    z.object({
        date: z.coerce.date(),
        filingDate: z.coerce.date(),
        acceptedDate: z.coerce.date(),
        symbol: z.coerce.string(),
        reportedCurrency: z.coerce.string(),
        cik: z.coerce.string(),
        fiscalYear: z.coerce.string(),
        period: z.coerce.string(),
        cashAndCashEquivalents: z.coerce.number(),
        shortTermInvestments: z.coerce.number(),
        cashAndShortTermInvestments: z.coerce.number(),
        netReceivables: z.coerce.number(),
        accountsReceivables: z.coerce.number(),
        otherReceivables: z.coerce.number(),
        inventory: z.coerce.number(),
        prepaids: z.coerce.number(),
        otherCurrentAssets: z.coerce.number(),
        totalCurrentAssets: z.coerce.number(),
        propertyPlantEquipmentNet: z.coerce.number(),
        goodwill: z.coerce.number(),
        intangibleAssets: z.coerce.number(),
        goodwillAndIntangibleAssets: z.coerce.number(),
        longTermInvestments: z.coerce.number(),
        taxAssets: z.coerce.number(),
        otherNonCurrentAssets: z.coerce.number(),
        totalNonCurrentAssets: z.coerce.number(),
        otherAssets: z.coerce.number(),
        totalAssets: z.coerce.number(),
        totalPayables: z.coerce.number(),
        accountPayables: z.coerce.number(),
        otherPayables: z.coerce.number(),
        accruedExpenses: z.coerce.number(),
        shortTermDebt: z.coerce.number(),
        capitalLeaseObligationsCurrent: z.coerce.number(),
        taxPayables: z.coerce.number(),
        deferredRevenue: z.coerce.number(),
        otherCurrentLiabilities: z.coerce.number(),
        totalCurrentLiabilities: z.coerce.number(),
        longTermDebt: z.coerce.number(),
        deferredRevenueNonCurrent: z.coerce.number(),
        deferredTaxLiabilitiesNonCurrent: z.coerce.number(),
        otherNonCurrentLiabilities: z.coerce.number(),
        totalNonCurrentLiabilities: z.coerce.number(),
        otherLiabilities: z.coerce.number(),
        capitalLeaseObligations: z.coerce.number(),
        totalLiabilities: z.coerce.number(),
        treasuryStock: z.coerce.number(),
        preferredStock: z.coerce.number(),
        commonStock: z.coerce.number(),
        retainedEarnings: z.coerce.number(),
        additionalPaidInCapital: z.coerce.number(),
        accumulatedOtherComprehensiveIncomeLoss: z.coerce.number(),
        otherTotalStockholdersEquity: z.coerce.number(),
        totalStockholdersEquity: z.coerce.number(),
        totalEquity: z.coerce.number(),
        minorityInterest: z.coerce.number(),
        totalLiabilitiesAndTotalEquity: z.coerce.number(),
        totalInvestments: z.coerce.number(),
        totalDebt: z.coerce.number(),
        netDebt: z.coerce.number(),
    }),
);

export const incomeSchema = z.array(
    z.object({
        date: z.coerce.date(),
        filingDate: z.coerce.date(),
        acceptedDate: z.coerce.date(),
        symbol: z.coerce.string(),
        reportedCurrency: z.coerce.string(),
        cik: z.coerce.string(),
        fiscalYear: z.coerce.string(),
        period: z.coerce.string(),
        revenue: z.coerce.number(),
        costOfRevenue: z.coerce.number(),
        grossProfit: z.coerce.number(),
        researchAndDevelopmentExpenses: z.coerce.number(),
        generalAndAdministrativeExpenses: z.coerce.number(),
        sellingAndMarketingExpenses: z.coerce.number(),
        sellingGeneralAndAdministrativeExpenses: z.coerce.number(),
        otherExpenses: z.coerce.number(),
        operatingExpenses: z.coerce.number(),
        costAndExpenses: z.coerce.number(),
        netInterestIncome: z.coerce.number(),
        interestIncome: z.coerce.number(),
        interestExpense: z.coerce.number(),
        depreciationAndAmortization: z.coerce.number(),
        ebitda: z.coerce.number(),
        ebit: z.coerce.number(),
        nonOperatingIncomeExcludingInterest: z.coerce.number(),
        operatingIncome: z.coerce.number(),
        totalOtherIncomeExpensesNet: z.coerce.number(),
        incomeBeforeTax: z.coerce.number(),
        incomeTaxExpense: z.coerce.number(),
        netIncomeFromContinuingOperations: z.coerce.number(),
        netIncomeFromDiscontinuedOperations: z.coerce.number(),
        otherAdjustmentsToNetIncome: z.coerce.number(),
        netIncome: z.coerce.number(),
        netIncomeDeductions: z.coerce.number(),
        bottomLineNetIncome: z.coerce.number(),
        eps: z.coerce.number(),
        epsDiluted: z.coerce.number(),
        weightedAverageShsOut: z.coerce.number(),
        weightedAverageShsOutDil: z.coerce.number(),
    }),
);

export const aftermarketTradeSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        price: z.coerce.number(),
        tradeSize: z.coerce.number(),
        timestamp: z.coerce.number(),
    }),
);

export const aftermarketQuoteSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        bidSize: z.coerce.number(),
        bidPrice: z.coerce.number(),
        askSize: z.coerce.number(),
        askPrice: z.coerce.number(),
        volume: z.coerce.number(),
        timestamp: z.coerce.number(),
    }),
);

export const changeSchema = z.array(
    z.object({
        symbol: z.coerce.string(),
        '1D': z.coerce.number(),
        '5D': z.coerce.number(),
        '1M': z.coerce.number(),
        '3M': z.coerce.number(),
        '6M': z.coerce.number(),
        ytd: z.coerce.number(),
        '1Y': z.coerce.number(),
        '3Y': z.coerce.number(),
        '5Y': z.coerce.number(),
        '10Y': z.coerce.number(),
        max: z.coerce.number(),
    }),
);
